### ISSUE TITLE
Retours incorrect sur recherche des communes par codeInsee

### ISSUE THREAD

**Issue by donaldinou** [etalab/geo.api.gouv.fr#100]
Bonjour,

Nous avons observé quelques incohérence sur la recherche par codeInsee avec l'api de recherche des communes.
Exemple:

```curl 'https://geo.api.gouv.fr/communes?code=13209'```

Ne nous retourne aucun résultat, alors que si nous nous voulons voir directement les informations de la commune (en l’occurrence un arrondissement), la commune existe et nous donne les informations désirées.

```curl 'https://geo.api.gouv.fr/communes/13209'```

**Comment by ThomasG77** [comment]
Bonsoir,

Vous pouvez essayer avec le endpoint en rajoutant une option `type=` qui donne l'URL https://geo.api.gouv.fr/communes?code=13209&type=commune-actuelle,arrondissement-municipal

Attention: si ce n'est pas dans la doc quelque part, c'est que la partie de l'API pour gérer les arrondissements n'a jamais été spécifiée et qu'elle peut être sujette à des changements dans le futur.
C'est pour cela que https://github.com/etalab/api-geo/issues/10 est toujours ouverte.

PS: ce dépôt c'est pour le site du même nom, le code de l'API Découpage Administratif et les issues liées sont sur https://github.com/etalab/api-geo
