### ISSUE TITLE
Certificat SSL expiré

### ISSUE THREAD

**Issue by Neo003** [etalab/geo.api.gouv.fr#103]
Bonjour,

Depuis peu, lorsqu'on arrive sur https://geo.api.gouv.fr, on a une erreur de certificat (sous Chrome / Windows 10):

![image](https://user-images.githubusercontent.com/54959041/161701532-5b634485-4857-4eb8-9601-555234392a37.png)

Je ne sais pas si c'est erreur est lié à l'expiration du certificat SSL ou au changement d'heure. Un renouvellement de certificat Let's Encrypt est peut-être nécessaire ?

**Comment by DavidViolet18** [comment]
Bonjour, 
idem de mon côté, il semblerait que le certificat soit expiré depuis ce matin 9h00

![image](https://user-images.githubusercontent.com/13423682/161702834-9f764fd0-6122-4524-9302-de3143a289c5.png)

**Comment by Neo003** [comment]
Ca fonctionne de nouveau. Le certificat a été mis à jour.

Merci.
