### ISSUE TITLE
Ajouter le code siren des communes dans la réponse api des routes communes

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/geo.api.gouv.fr#106]
Il est souvent pratique de pouvoir faire le lien entre le numéro siren d'une commune et son code INSEE et il n'existe pas de moyens facile de le faire actuellement.

Cette correspondance est pourtant faite par la DGCL et est disponible sur cette page : 
 https://www.banatic.interieur.gouv.fr/V5/fichiers-en-telechargement/fichiers-telech.php (lien "Table de correspondance code SIREN / Code Insee des communes" sur le côté gauche dans les documents associés)

J'ai fais un petit script python pour récupérer et nettoyer les données (à adapter) : https://github.com/geoffreyaldebert/correspondance-commune-siren-insee/blob/master/Correspondance%20Commune%20n%C2%B0%20SIREN%20-%20Code%20Insee.ipynb

Le fichier de sortie est un csv qui contient deux colonnes siren et insee : https://github.com/geoffreyaldebert/correspondance-commune-siren-insee/blob/master/correspondance-commune-code-insee-siren.csv

Serait-il possible d'ajouter cette propriété `siren` dans l'API ?

**Comment by geoffreyaldebert** [comment]
@jdesboeufs me souffle à l'oreille que cette correspondance existe aussi sur https://www.collectivites-locales.gouv.fr/institutions/liste-et-composition-des-epci-fiscalite-propre qui est déjà utilisé dans le repo. Cela me semble donc plus simple de partir de ce fichier si les données sont exhaustives.

**Comment by ThomasG77** [comment]
Pour la complétude du fichier qui est déjà dans le dépôt,

```
curl -s "https://unpkg.com/@etalab/decoupage-administratif/data/epci.json" | jq -c .[].membres epci.json | jq -c .[] - | wc -l
```
retourne 34951 communes

Formatté en CSV

```
curl -s "https://unpkg.com/@etalab/decoupage-administratif/data/epci.json" | jq -c .[].membres epci.json | jq -c .[] - | jq -c -r '[.siren, .code] | @csv' - | sed 's#"##g' >| collectivites-locales.csv
```

En comparant à ton fichier

```
sed '1d' correspondance-commune-code-insee-siren.csv | wc -l
```

on a 34955 communes donc 4 d'écart

Pour voir le détail
```
diff <(sed '1d' correspondance-commune-code-insee-siren.csv | sort) <(sort collectivites-locales.csv)
```

et voilà les 4 communes de différences qui sont concernées

```
212200166,22016
212900831,29083
212901557,29155
218501138,85113
```

**Comment by geoffreyaldebert** [comment]
Que des îles ! Trop bizarre

**Comment by ThomasG77** [comment]
https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Commune_hors_intercommunalit%C3%A9_%C3%A0_fiscalit%C3%A9_propre_en_France

**Comment by ThomasG77** [comment]
Doublon de https://github.com/etalab/api-geo/issues/164
Plus d'infos ici donc je garde ouvert ici

**Comment by geoffreyaldebert** [comment]
👏  🙏
