### ISSUE TITLE
Ajouter les nouvelles communes

### ISSUE THREAD

**Issue by seb-jean** [etalab/geo.api.gouv.fr#110]
Bonjour,

8 nouvelles communes ont été créé :

- Bernoy-le-Château
- Bonnay-Saint-Ythaire
- Bézac
- Coeur-de-la-Vallée
- Culoz-Béon
- Mansle-les-Fontaines
- Terval
- Tourneville-sur-Mer

Il serait intéressant de les intégrer 😃

**Comment by jdesboeufs** [comment]
Bonjour,

Le Code Officiel Géographique 2023 sera publié par l'INSEE dans quelques jours. D'ici là rien ne peut être fait sans certitude.

**Comment by AxelP-projects** [comment]
Bonjour, 
je ne vois pas les nouvelles communes apparaitre, ni les communes fermées disparaitre. Avez-vous pu intégrer les changements de 2023?
Merci et bonne journée.

**Comment by ThomasG77** [comment]
Les changements ont été effectués il y a maintenant quelques mois. Je ferme
