### ISSUE TITLE
AJOUT API COLLECTIVITES OUTRE MER

### ISSUE THREAD

**Issue by justin83** [etalab/geo.api.gouv.fr#114]
Bonjour, 
Est-il envisagé d'ajouter une API pour lister les collectivités territoriales d'outre-mer SVP ?

En effet, si je prends l'exemple de la nouvelle calédonie, ce n'est pas une région donc elle n'apparait pas dans votre API région mais quand je consulte l'API communes, je trouve une code région 988. 

Je voudrais pouvoir faire ressortir la collectivité avec ce code région. 

Cordialement.

**Comment by ThomasG77** [comment]
C'est déjà possible. Essayez https://geo.api.gouv.fr/communes?zone=metro,drom,com&codeRegion=988
