### ISSUE TITLE
Amélioration de la recherche pour les villes ayant des espaces ou des tirets dans leur nom

### ISSUE THREAD

**Issue by CamilleLegeron** [etalab/geo.api.gouv.fr#115]
Bonjour,

En testant l'API découpage administratif je me rend compte qu'il semble y avoir une mauvaise gestion des espaces et tirets dans les noms des communes. 
Par exemple, avec `La Rochelle` ou `La%20Rochelle` le score de confiance est à 0.05 ou 0.09, si
j'écris `Rochelle` ce score passe à 0.95 mais `LaRochelle` ne donne aucun résultat.
J'ai également fait des tests avec `Saint-Martin`, et le score le plus fiable est de 0.31 et donne la ville de `Saint-Martinien`

Merci

**Comment by vviers** [comment]
ping @ThomasG77 ?
