### ISSUE TITLE
Le filtre type=housenumber ne fonctionne pas

### ISSUE THREAD

**Issue by raphaelbadia** [etalab/geo.api.gouv.fr#33]
Bonjour,

Je suis en train d'implémenter l'api et je souhaite récupérer une liste de numéros de rues.

J'ai donc filtré par "housenumber" : https://api-adresse.data.gouv.fr/search?q=121%20rue%20past&type=housenumber

j'obtient des résultats de type "street" au lieu de résultats de type "housenumber".

Je pense que je devrais avoir des suggestions pour des `121 rue pasteur` de différentes villes au lieu d'avoir simplement des rues.

**Comment by AMontagu** [comment]
Aucune nouvelle sur ce point ?

**Comment by jdesboeufs** [comment]
Bonjour,

Je vous suggère fortement d'ouvrir une issue sur le dépôt qui concerne le géocodeur : https://github.com/addok/addok
Désolé pour l'absence de clarté des dépôts, on y travaille. Les équipes ne sont pas forcément les mêmes.
