### ISSUE TITLE
Coordonnée dans les résultats inversés 

### ISSUE THREAD

**Issue by bouteillerAlan** [etalab/geo.api.gouv.fr#41]
Lorsqu'une recherche est effectuée via un paramètre : 

*exemple : `https://api-adresse.data.gouv.fr/search/?q='75 rue de la madeleinne'&postcode=49000`*

le résultat renvoie dans `features.geometry.coordinates` des coordonnée juste mais inversé.

Dans le cas de l'exemple plus haut j'ai comme réponse `-0.53974, 47.462158` ce qui correspond à une position proche de la Somalie alors que si j'inverse cela me donne les bonne coordonnées (`47.462158, -0.53974`).

**Comment by jdesboeufs** [comment]
Bonjour,
L’ordre des coordonnées est conforme à la spécification GeoJSON, à savoir longitude en premier.
Cordialement.
