### ISSUE TITLE
Erreur de colonne dans la doc

### ISSUE THREAD

**Issue by pyrog** [etalab/geo.api.gouv.fr#44]
Dans [components/adresse/curl-doc.js#L126](https://github.com/etalab/geo.api.gouv.fr/blob/master/components/adresse/curl-doc.js#L126) la colonne **score** est  nommée `result_score`

**Comment by ThomasG77** [comment]
Erreur corrigée depuis https://adresse.data.gouv.fr/api-doc/adresse
