### ISSUE TITLE
Quand une ville n'est pas trouvé, l'API HTTP retourne quand même un code 200

### ISSUE THREAD

**Issue by DavidBruant** [etalab/geo.api.gouv.fr#51]
Je pense à https://geo.api.gouv.fr/communes?nom=Biscarosse&boost=population&limit=1 par exemple, qui retourne actuellement un 200 avec `[]` comme *body* et qui mériterait peut-être un `404 not found`

**Comment by DavidBruant** [comment]
(et il s'agit d'une typo. La commune s'écrit "Biscarrosse")

**Comment by jdesboeufs** [comment]
Bonjour.
Cette partie de l’API est une API de recherche. Il est d’usage de retourner une 200 avec un tableau vide lorsqu’aucun résultat ne correspond.
Pour les autres URL nous utilisons bien le 404 lorsqu’aucune ressource ne se trouve à l’URL indiquée.
Merci pour votre retour.
