### ISSUE TITLE
Recherche des communes par région

### ISSUE THREAD

**Issue by iOiurson** [etalab/geo.api.gouv.fr#53]
Le endpoint `/regions/{codeRegion}/communes` ne fonctionne pas.

https://geo.api.gouv.fr/regions/11/communes

**Comment by mhollebecq** [comment]
Meme souci. La route semble bonne car l'erreur remontée est différente de celle remontée lors d'une requete sur un faux endpoint

**Comment by Ombrelin** [comment]
Même problème chez moi, et en effet ça n'est pas la 404 classique : 

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /regions/53/communes</pre>
</body>
</html>
```

**Comment by iOiurson** [comment]
Le endpoint a été retiré lors de #86
