### ISSUE TITLE
Avoir aussi les arrondissements avec les communes

### ISSUE THREAD

**Issue by khalilou88** [etalab/geo.api.gouv.fr#57]
Bonjour,

Je veux avoir la liste des communes pour un departement donné.
Pour le departement de paris j'ai une seule reponse qui est paris aussi.

J'aimerais avec les arrondissement aussi. Y a une solution pout cela?

Merci

**Comment by ThomasG77** [comment]
Bonjour,

Sauf erreur, voilà comment faire actuellement https://geo.api.gouv.fr/communes?type=arrondissement-municipal,commune-actuelle&fields=nom,code,codeDepartement,siren,codeEpci,codeRegion,codesPostaux,population,anciensCodes,codeParent&codeDepartement=75
