### ISSUE TITLE
Problème de recherche pour les villes avec plusieurs codes postaux

### ISSUE THREAD

**Issue by FDR29** [etalab/geo.api.gouv.fr#62]
Bonjour, 

la recherche par code postal ou ville ne fonctionne pas semble-t-il quand une ville peut être associée à plusieurs codes postaux : exemple Toulouse, Nantes, Lille, ...
Pour Toulouse, par exemple, la recherche par un code postal existant
https://api-adresse.data.gouv.fr/search/?q=31200&type=municipality
nous restitue : 
"id": "31555", "type": "municipality", "name": "Toulouse", "postcode": "31500"

Pour la recherche suivante : 
https://api-adresse.data.gouv.fr/search/?q=toulouse&type=municipality
il n'y a qu'un seul résultat correspondant à la ville de Toulouse avec aussi au CP 31500

Comment devons-nous procéder pour avoir une liste complète des CP pour une ville qui en propose plusieurs? 

Par avance, merci de votre retour et de votre aide.

Frédéric

**Comment by jdesboeufs** [comment]
Bonjour,

Le filtre `postcode` est à utiliser pour les adresses.

Si vous voulez faire une recherche de communes par code postal, vous devriez utiliser l'API Communes.
https://geo.api.gouv.fr/communes?codePostal=31200
https://geo.api.gouv.fr/communes?nom=toulouse&boost=population

La documentation est ici : https://geo.api.gouv.fr/decoupage-administratif/communes

**Comment by FDR29** [comment]
Bonjour 
Merci pour votre retour rapide !

En fait nous utilisons ceci : https://api-adresse.data.gouv.fr.
Et viens de me rendre compte que n'ai pas forcément posé ma question au bon endroit. 
J'aurais du la poser  là : etalab /adresse.data.gouv.fr.

Donc si nous continuons à utiliser https://api-adresse.data.gouv.fr, y a t-il un moyen de répondre à ma problématique.

Merci

Frédéric
