### ISSUE TITLE
L'endpoint /search/csv géocode mal en cas d'apostrophe courbe

### ISSUE THREAD

**Issue by vdegove** [etalab/geo.api.gouv.fr#71]
Pour deux fichiers identiques, avec colonne unique à géocoder, l'adresse "189 rue d’Aubervilliers, 75018 Paris" (avec apostrophe courbe) va être incorrectement géocodée au 189 rue Belliard, 75018 tandis que "189 rue d'Aubervilliers, 75018 Paris" va l'être au bon endroit.

Exemple :

```
➜  Téléchargements cat exempleBANCSV.csv 
Adresses
"189 Rue d'Aubervilliers, 75018 Paris"
"18 Rue de Sambre-Et-Meuse, 75010 Paris"
➜  Téléchargements curl -X POST -F data=@exempleBANCSV.csv https://api-adresse.data.gouv.fr/search/csv/
Adresses,latitude,longitude,result_label,result_score,result_type,result_id,result_housenumber,result_name,result_street,result_postcode,result_city,result_context,result_citycode,result_oldcitycode,result_oldcity,result_district
"189 Rue d'Aubervilliers, 75018 Paris",48.896641,2.370134,189 Rue d’Aubervilliers 75018 Paris,0.98,housenumber,75118_0517_00189,189,Rue d’Aubervilliers,,75018,Paris,"75, Paris, Île-de-France",75118,,,Paris 18e Arrondissement
"18 Rue de Sambre-Et-Meuse, 75010 Paris",48.875002,2.370747,18 Rue de Sambre-et-Meuse 75010 Paris,0.97,housenumber,75110_8801_00018,18,Rue de Sambre-et-Meuse,,75010,Paris,"75, Paris, Île-de-France",75110,,,Paris 10e Arrondissement
➜  Téléchargements cat exempleBANapostrophecourbe.csv 
Adresses
"189 Rue d’Aubervilliers, 75018 Paris"
"18 Rue de Sambre-Et-Meuse, 75010 Paris"
➜  Téléchargements curl -X POST -F data=@exempleBANapostrophecourbe.csv https://api-adresse.data.gouv.fr/search/csv/ 
Adresses,latitude,longitude,result_label,result_score,result_type,result_id,result_housenumber,result_name,result_street,result_postcode,result_city,result_context,result_citycode,result_oldcitycode,result_oldcity,result_district
"189 Rue d’Aubervilliers, 75018 Paris",48.895555,2.329227,189 Rue Belliard 75018 Paris,0.55,housenumber,75118_0838_00189,189,Rue Belliard,,75018,Paris,"75, Paris, �le-de-France",75118,,,Paris 18e Arrondissement
"18 Rue de Sambre-Et-Meuse, 75010 Paris",48.875002,2.370747,18 Rue de Sambre-et-Meuse 75010 Paris,0.97,housenumber,75110_8801_00018,18,Rue de Sambre-et-Meuse,,75010,Paris,"75, Paris, �le-de-France",75110,,,Paris 10e Arrondissement
➜  Téléchargements 
```

**Comment by sallesma** [comment]
Le problème n'est pas présent sur le endpoint `/search`

Les requêtes pour 
- http://api-adresse.data.gouv.fr/search/?q=189%20Rue%20d%27Aubervilliers,%2075018%20Paris
- http://api-adresse.data.gouv.fr/search/?q=189%20Rue%20d%E2%80%99Aubervilliers,%2075018%20Paris

me semblent renvoyer le même résultat

**Comment by chtitux** [comment]
## Python 2
```
[theophile:~] $ python2.7
Python 2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.findall(r".", "’")
['\xe2', '\x80', '\x99']
```

## Python 3
```
[theophile:~] $ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.findall(r".", "’")
['’']
>>> 
```

Je n'ai aucune idée de si le problème est lié à la version de Python, mais [`’`](https://www.fileformat.info/info/unicode/char/2019/index.htm) est compté comme "3 caractères" par Python 2.7.

Du coup, ça ne tokenize pas correctement:
```
$ python2.7
>>> PATTERN.findall("189 Rue d'Aubervilliers, 75018 Paris")
['189', 'Rue', 'd', 'Aubervilliers', '75018', 'Paris']
>>> PATTERN.findall("189 Rue d’Aubervilliers, 75018 Paris")
['189', 'Rue', 'd\xe2', 'Aubervilliers', '75018', 'Paris']
```

`PATTERN` vient de https://github.com/addok/addok/blob/bb205e7/addok/helpers/text.py#L14

**Comment by vdegove** [comment]
Issue à priori ouverte sur le mauvais dépôt, je l'ai donc recréée ici https://github.com/addok/addok/issues/667

**Comment by jdesboeufs** [comment]
On a un oeil sur les deux mais merci !

**Comment by vdegove** [comment]
@jdesboeufs oh, merci pour le message ! En réalité j'ai juste cliqué sur l'icône Github en bas de la doc, pis je me suis retrouvé ici, j'ai vu un bouton nouvelle issue, et hop. Ensuite on m'a expliqué le coup de Addok. Vous préférez les mails sinon pour les rapports de bug / feature request / etc ou les issues Github ? D'AILLEURS en feature request liée, ça serait très chouette de pas avoir à créer de fichier CSV et juste envoyer du JSON en paramètre POST pour le géocoding en batch.
