### ISSUE TITLE
Probleme sur Papeetee et d'autres villes d'Outre Mer

### ISSUE THREAD

**Issue by MarineMazeaud** [etalab/geo.api.gouv.fr#91]
Bonjour, 

Je n'arrive pas à récupérer les informations de certaines villes d'Outre mer.

https://geo.api.gouv.fr/communes?fields=code&format=json&nom=PAPEETE&codeDepartement=987 ne renvoie rien 

Or https://geo.api.gouv.fr/communes?fields=code&format=json&nom=PAPEETE fonctionne et son code postal est 98735. 

Même souci pour MARE

https://geo.api.gouv.fr/communes?fields=code&format=json&nom=MARE&codeDepartement=988 ne renvoie rien alors que

https://geo.api.gouv.fr/communes?fields=code&format=json&nom=MARE renvoie bien la commune de Maré avec 98815 en code postal.

Même souci pour Pukapuka

https://geo.api.gouv.fr/communes?fields=code&format=json&nom=PUKA+PUKA&codeDepartement=987 non trouvé alors que https://geo.api.gouv.fr/communes?fields=code&format=json&nom=PUKA+PUKA est trouvé et renvoie le code postal 98737.

Même souci pour Sigave

https://geo.api.gouv.fr/communes?fields=code&format=json&nom=SIGAVE&codeDepartement=986 ne répond pas alors que https://geo.api.gouv.fr/communes?fields=code&format=json&nom=SIGAVE répond et fourni le code postal 98612

**Comment by MarineMazeaud** [comment]
Idem pour https://geo.api.gouv.fr/communes?fields=code&format=json&nom=UTUROA&codeDepartement=987

**Comment by ThomasG77** [comment]
Bonjour,

Sauf erreur, c'est résolu depuis. Libre à vous de réouvrir.
